name: LondonBBD_test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31427675765007734
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#290b0b'
    - '#fdf4a5'
    - '#baa043'
    - '#c65d1b'
    - '#078a9e'
  brandStrength: 0.8953642121050507
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
